export const VALIDATE_PROFILE = 'VALIDATE_PROFILE';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const UNSET_PROFILE = 'UNSET_PROFILE';

export const UPDATE_LOGIN_INPUT = 'UPDATE_LOGIN_INPUT';

export const ADD_OPTION_TO_SURVEY_FORM = 'ADD_OPTION_TO_SURVEY_FORM';
export const REMOVE_OPTION_FROM_SURVEY_FORM = 'REMOVE_OPTION_FROM_SURVEY_FORM';
export const UPDATE_SURVEY_INPUT = 'UPDATE_SURVEY_INPUT';

export const TOGGLE_SURVEY_FORM = 'TOGGLE_SURVEY_FORM';
export const SAVE_SURVEY = 'SAVE_SURVEY';
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const SET_SURVEYS = 'SET_SURVEYS';
export const RESET_SURVEY_FORM = 'RESET_SURVEY_FORM';
export const TOGGLE_SURVEY = 'TOGGLE_SURVEY';

export const SAVE_ANSWER = 'SAVE_ANSWER';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const FETCH_ANSWERS = 'FETCH_ANSWERS';
export const SET_ANSWERS = 'SET_ANSWERS';

export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';